CDOT-CV/jpo-ode

jpo-ode-core/src/main/java/us/dot/its/jpo/ode/model/OdeLogMetadata.java
jpo-ode-core/src/main/java/us/dot/its/jpo/ode/model/OdeTimMetadata.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeMessageJSON.java

Created new TIM Metadata class

---

jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/OdeSvcsApplication.java

Bug fix for [#458](https://github.com/usdot-jpo-ode/jpo-ode/issues/458). The update to the SNMP library version removed some of the default authentication protocols which are less secure. As it happens, we use those and need them added.
https://github.com/usdot-jpo-ode/jpo-ode/issues/458
Communication via SNMP to RSUs is prohibited with the latest update in SNMP library version. This PR addresses the issue by adding back in some default (albeit less secure) authentication protocols.
Tested local, and in WYDOT dev environment.

Testing authentication protocal addition

---

jpo-ode-core/src/main/java/us/dot/its/jpo/ode/dds/DepositResponseDecoder.java
jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/BitStringBuilder.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1CommandManager.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/AbstractAsn1DecodeMessageJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeBSMJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeMAPJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSPATJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSRMJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSSMJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeTIMJSON.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/snmp/SnmpSession.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/storage/FileSystemStorageService.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/bsm/BsmReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/map/MapReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/spat/SpatReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/srm/SrmReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/ssm/SsmReceiver.java

This update handles swapping out message level detail from INFO in favor of DEBUG.
https://github.com/usdot-jpo-ode/jpo-ode/issues/471
Tested locally.

Logging Level Updates

---

jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/BitStringBuilder.java

Swapping log statement away from warn to debug as it provides data and not a true warning.

Swapping warn down to debug to reflect non-threat

---

jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/traveler/TimDepositController.java

Allow unknown properties when converting JSON object to a POJO and handle the resulting exception that may be thrown.

Allow unknown properties when converting from JSON

---

jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/traveler/TimDepositControllerTest.java

A unit test for the TimDepositController class for depositing a TIM with extra properties has been added to `TimDepositControllerTest.java`.
Additionally, the input json string for a test involving invalid json syntax has been modified.

Added unit test for depositing TIM with extra properties.

---

jpo-ode-core/src/main/java/us/dot/its/jpo/ode/dds/CASClient.java
jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/OdePluginImpl.java
jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/TravelerMessageFromHumanToAsnConverter.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/OdeProperties.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/heartbeat/RsuSnmp.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/storage/FileSystemStorageService.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/bsm/BsmReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/map/MapReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/spat/SpatReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/srm/SrmReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/ssm/SsmReceiver.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/tim/TimReceiver.java

Reviewed specified log levels for each log statement. In cases where another log level was more fitting, the log level being used was switched.
No related issue.
The motivation for these changes is to ensure that we aren't logging messages unnecessarily and that we are logging messages correctly when we are on a particular log level.
- The unit tests have been verified to pass locally.
- This has been deployed in our dev cluster and data has been verified to continue flowing.

Log Level Review

---

README.md

Updating required host machine OS versions.
No related issue.
Changes recommendation for host machines to use more secure OS versions.
Verified with recommended docker installation OS versions.

README Operating System Updates

---

.devcontainer/post-create.sh
jpo-ode-core/src/main/resources/schemas/schema-psm.json
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/coder/stream/LogFileToAsn1CodecPublisher.java
jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/importer/parser/PayloadParser.java

- Adding clarity to the log offloading new line character removal logic. 
- Added ENUM values in the PSM data type schema
- Added all required kafka topic creation to the dev container
- Moved hard coded payload start values into constant definitions for clarity
N/A
To merge into USDOT branch
Tested log processing in docker and ran related unit tests in the dev container
- [  ] I have added any new packages to the sonar-scanner.properties file
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

USDOT PSM/Log Offloading Fixes

---

jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/importer/parser/PayloadParser.java

Fixing Log processing logic, exits the if statement but allows the for loop to iterate over all data types.
N/A
To process offloaded Commsignia log files
Build and test the log processing with "_commsignia" log files in the data directory

Log processing bug fix

---

.github/workflows/artifact-publish.yml
README.md
pom.xml

Adding maven JAR publishing to GitHub Maven Central.
To allow for less reliance on Git submodules when needing jpo-ode artifacts
Tested a trigger manually and pulling the generated jar files
- [ x ] New feature (non-breaking change that adds functionality)
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] All new and existing tests passed.

GitHub actions artifact publishing

---

docs/compatibility.md

An entry has been added to the submodule compatibility guide for version 3.0.0 of the ODE.
No related issue.
The submodule compatibility guide is intended to be an informative resource for users seeking to run the ODE & its submodules. This resource should remain up to date as new releases come out.
Documentation change, no testing necessary.

Submodule Compatibility Guide Entry for ODE 3.0.0

---

jpo-ode-common/pom.xml
jpo-ode-core/pom.xml
jpo-ode-plugins/pom.xml
jpo-ode-svcs/pom.xml
jpo-ode-svcs/run.bat
jpo-ode-svcs/run.sh
pom.xml

Upgraded the POM version to the next major version due to the repository's backwards incompatibility for the next quarterly release.
N/A
This is required due to backwards incompatibility and the need for a new version number to trigger GitHub to build a new artifact for this repository.
N/A

Update POM Version 4.0.0

---

.github/workflows/artifact-publish.yml
.github/workflows/ci.yml
.github/workflows/dockerhub.yml

Adds caching to [docker](https://docs.docker.com/build/cache/backends/gha/#using-dockerbuild-push-action) and [maven](https://github.com/actions/setup-java#caching-packages-dependencies) builds.
N/A
To reduce time wasted for GitHub to finish building docker files/artifacts
Previous repositories, conflictmonitor, conflictvisualizer, etc.

GitHub Actions Caching

---

jpo-ode-core/src/main/resources/schemas/schema-map.json
jpo-ode-core/src/main/resources/schemas/schema-tim.json

More schema fixes that have been found working with the ADAP team. This should be the last fix before the quarterly.
N/A
Current schemas are not perfectly conforming to the ODE message output.
Schema checker with messages going through the CDOT environment.

TIM and Map Schema Fixes #2

---

.azure/README.md
.azure/azure-pipelines.yml
azure-pipelines.yml

Add's an azure pipeline configuration file to allow for CI through Devops.
N/A
Remove reliance of local docker image build for CDOT deployments.
This will use a similar workflow as the CV manager uses and most of the logic is handled in Devops.

Set up CI with Azure Pipelines

---

jpo-ode-common/pom.xml
jpo-ode-core/pom.xml
jpo-ode-plugins/pom.xml
jpo-ode-svcs/pom.xml
pom.xml

Updated the version in pom.xml files from 4.0.0 to 4.1.0 to reflect the latest release.
Verified successful compilation, passing unit tests & startup using `docker compose up --build`

Update project version to 4.1.0

---

docs/Release_notes.md

This PR updates the release notes in preparation for the 2025 Q2 release.

Prepare release notes for 2025 Q2 release

---

jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/kafka/producer/InterceptingKafkaTemplate.java

Lowers the severity of the log message for a Kafka write body not being JSON or including the 'originIp' field. This is a metric that is collected for all topics, not just JSON topics, but looks to enhance the metrics that do include 'originIp'. Lowering the log severity to INFO allows for the message to be seen if logging is set appropriately but ignored in a deployment scenario since it is unnecessary to see to ensure that Kafka message production is functional.
CDOT BUG 316154
This is required to reduce the verbosity of a fairly common error log whenever a TIM is deposited through the jpo-ode.
This has been tested locally with the /tim endpoint.

Deescalate the error log since it is excessive and well handled already

---

docs/release_process_quarterly.md

Adds instructions for releasing the jpo-asn-pojos library to the quarterly release instructions.
The `jpo-asn-pojos` project is a new library that it is planned for the ODE to depend on.  The current release documents instructions don't include it.
This PR only changes markdown files.  It was tested by viewing the file, and running the existing unit tests.

Document jpo-asn-pojos release process

---

docs/release_process_quarterly.md

Enhanced the release checklist to clarify HTTP endpoint testing and added detailed validation steps for TIM processing through the pipeline. Also included verification for multi-instance ODE operation with Kafka to prevent conflicts.
Some issues were discovered after the latest release of the JPO ODE ecosystem. These could have been caught earlier if the release process had included testing for multi-instance deployments and signed TIMs. Adding these validation steps to the release process will help prevent similar problems in the future.
Documentation change, no testing necessary.

Update release process documentation with new validation steps

---

jpo-ode-common/pom.xml
jpo-ode-core/pom.xml
jpo-ode-plugins/pom.xml
jpo-ode-svcs/pom.xml
pom.xml

Integrates the latest bug fix from the jpo-asn-pojos project regarding the handling of open type XML deserialization of special characters, such as '&'.
- The jpo-ode-svcs module has had two `org.apache.commons` dependencies added. This is required to support the new jpo-asn-pojos serialization changes within the `Asn1DecoderRouter` class.
- The jpo-ode version has been incremented across all modules.
N/A
Example Map messages that contained '&' characters failed to be serialized and written to the `topic.OdeMapJson` topic.
Example Map: `001282ab780cc3780302071583b3869dd95048efe5026411504dc3a7720a7d02f120d4db5ec1728a71ddd462402dc0514f8d16010a0d0001000102db49fb2d3693fe40b9fdf1c5bd6ec22cac71216343610b1459703ec52e0b2556403915340243a00008b00c50680008000816c7447969ba1ff345cc4f9a2dd476d164ab8b8b1 …

Bug Fix: Support open type XML deserialization of special characters
