- jpo-ode-common/src/test/java/us/dot/its/jpo/ode/util/SerializationUtilsTest.java
- jpo-ode-common/src/test/java/us/dot/its/jpo/ode/util/TestData.java
An inner class was causing one of the tests to fail. This class has been moved to its own file.
There is no issue for this problem.
I was testing how the ODE would work with an updated librdkafka library when I ran into this.
The unit tests have been run and verified to pass.
> Bug Fix - Referencing Error in SerializationUtilsTest.java

- jpo-ode-core/src/main/java/us/dot/its/jpo/ode/model/OdeSpatMetadata.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/coder/OdeSpatDataCreatorHelper.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/coder/stream/LogFileToAsn1CodecPublisher.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/importer/parser/LogFileParser.java
This fixes the duplication of the JSON field for "isCertPresent" for SPaT messages. Previously, "isCertPresent" was being duplicated by having another field named "certPresent". This was due to method names being inconsistent. This fix both adds a Jackson annotation for ensuring the output schema is correct and alters the method names slightly to make them more consistent with Java development standards for getters and setters.
> SPaT Serialization Bug

- jpo-ode-common/src/main/java/us/dot/its/jpo/ode/util/JsonUtils.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/traveler/TimTransmogrifier.java
The Jackson library by default does not allow for extraneous properties when deserializing. This helps prevent issues that may arise with improper data formats, however we require this ability when pushing a TIM through. In the TimTransmogrifier, we deserialize an OdeTravelerInputData object into a TravelerInputData object. The ODE version has additional fields that we want to simply drop during this deserialization. This PR adds an override to the JsonUtils.jacksonFromJson method to allow ignoring extraneous properties.
Tested locally, as well as in the WYDOT development environment. 
> Adding ability to ignore unknown properties when deserializing

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
The purpose of this PR is to make it possible to debug C++ projects in the ODE's dev container environment. With these changes, it should now be possible to run C++ code that lives in the ACM and PPM submodules when in the dev container.
The following packages are now installed in the dev container upon building the image:
- g++
- cmake
- libsasl2-dev
- libsasl2-modules
- libssl-dev
- librdkafka-dev
- autoconf
- libtool
The following extensions will now be accessible in the dev container:
- ms-vscode.cpptools
- ms-vscode.cmake-tools
> C++ Debugging Support in Dev Container

- docs/schemas/README.md
- jpo-ode-core/src/main/resources/schemas/schema-bsm.json
- jpo-ode-core/src/main/resources/schemas/schema-filtered-bsm.json
The 'filtered-bsm-schema.json' file has been introduced, which does not contain members that are redacted by the PPM's general redaction functionality.
> Filtered BSM Schema

- jpo-ode-core/src/main/resources/schemas/schema-bsm.json
Reverts the BSM schema back to what it was originally. Keeps the removal of filtered BSM since it is no longer needed.
> Revert BSM schema

- docker-compose-confluent-cloud.yml
- docker-compose-ppm-nsv.yml
- docker-compose.yml
The DOCKER_SHARED_VOLUME_WINDOWS environment variable is no longer needed.
The DOCKER_SHARED_VOLUME_WINDOWS environment variable has been removed.
Spinning up the project using docker-compose has been verified to work with these changes.
> Removed DOCKER_SHARED_VOLUME_WINDOWS env var

- docs/Release_notes.md
Release notes for the upcoming v1.6.0 release have been added to `docs/Release_notes.md`
> Release Notes for v1.6.0

- jpo-ode-common/pom.xml
- jpo-ode-core/pom.xml
- jpo-ode-plugins/pom.xml
- jpo-ode-svcs/pom.xml
- jpo-ode-svcs/run.bat
- jpo-ode-svcs/run.sh
- pom.xml
The version in the pom.xml files are outdated.
The version have been updated to 1.6.0-SNAPSHOT in the following files:
- jpo-ode-common/pom.xml
- jpo-ode-core/pom.xml
- jpo-ode-plugins/pom.xml
- jpo-ode-svcs/pom.xml
- jpo-ode-svcs/run.bat
- jpo-ode-svcs/run.sh
- pom.xml
The tests pass & the project compiles.
The 'release.properties' file still needs to be updated by running `mvn release:prepare`, but this isn't working for me so we may have to leave it for USDOT.
> Changed version to 1.6.0-SNAPSHOT

- jpo-ode-core/src/test/java/us/dot/its/jpo/ode/snmp/SNMPTest.java
- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/SNMP.java
This includes an update to snmpTimestampFromIso to trim nanoseconds to a length of two. This fixes an issue that was discovered when a timestamp of the form YYYY-MM-DDTHH:mm:ss.sssZ is passed to this method. 
An additional unit test was added to test this method with a timestamp of the form YYYY-MM-DDTHH:mm:ss.sssZ. 
- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ X ] I have added tests to cover my changes.
- [ X ] All new and existing tests passed.
> Trim Nanoseconds from snmpTimestampFromIso

- docs/dockerhub.md
The dockerhub documentation for the project references submodules, but does not provide guidance on what versions of the submodules to use.
A link to the 'Submodule Compatibility Guide' has been added to the dockerhub documentation. This is currently linking to the CDOT fork, as the guide does not yet exist in the parent project. A local reference would have been used, but the dockerhub documentation is expected to be posted on the DockerHub page for the ODE image, so a direct link is more suited here.
Users who are reading the dockerhub documentation should be aware of the Submodule Compatibility Guide.
Clicking on the link has been verified to properly redirect to the blob page on the dev branch of CDOT's fork.
[ODE Contributing …
> Added 'Submodule Compatibility Guide' link to dockerhub documentation

- pom.xml
This PR updates the maven-sonar-plugin, maven-surefire-plugin, and maven-release-plugin versions to the latest available version.
There have been periodic sonar failures in the jpo-ode repository. Updating these plugins to the latest version should minimize the frequency of these failures. 
This has been tested by observing the output of the sonar pipeline in Github.
- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ X ] I have read the **CONTRIBUTING** document.
- [ X ] All new and existing tests passed.
> Update Maven Plugin Versions

- docker-compose-ppm-nsv.yml
- docker-compose.yml
- scripts/kafka/kafka_init.sh
This PR updates the docker-compose files to include an additional service responsible for creating Kafka topics on startup. 
This change fixes an issue where some topics were not created when running Kafka. Additionally, an on-restart policy has been added to the AEM and ADM so that they will continually try reconnecting until their topic is ready.
This has been tested locally using docker compose.
- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ X ] I have read the **CONTRIBUTING** document.
- [ X ] All new and existing tests passed.
> Update Kafka topic creation

- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/RoadSideUnit.java
- jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/traveler/TimDepositControllerTest.java
The ODE is running into an infinite recursion error when serializing the RSU class, despite the apparent absence of circular dependencies within it. Jackson attempts to serialize the 'logger' field of the RSU class at this time. The Logger class was likely not intended for serialization and attempting to serialize it causes the error.
The 'logger' field of the RSU class now has a JsonIgnore annotation. This instructs Jackson to exclude this field during object serialization.
This fix is necessary to ensure proper JSON serialization by the ODE, which is necessary for data flow.
- A unit test has been added to the TimDepositControllerTest class that uses a JSON payload with the 'rsu' element populated to ensure that RSU serialization gets tested. This new test and …
> RSU Serialization Fix

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/rsu/RsuDepositor.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/snmp/SnmpSession.java
We're encountering numerous 'authEngineID is null' errors in our GCP environments. Often, these errors occur when the RSU is unreachable. This overlap between RSU unavailability and the 'authEngineID is null' error complicates identifying genuine authEngineID retrieval failures.
The SnmpSession class has been updated to address this issue. Now, regardless of whether the authoritative engine ID can be retrieved beforehand, a request will always be sent to the RSU. Failure to retrieve the authoritative engine ID will only be logged if we receive a response from the RSU. In instances where the RSU is unreachable, failure to retrieve the authoritative engine ID will not be logged anymore.
Upon encountering a miscellaneous error status code from the RSU, context will now be provided in the …
> Report authEngineID retrieval failure only if response is received

- sample.env
The comment associated with the KAFKA_TYPE environment variable is incorrect and misleading at this time.
The comment associated with the KAFKA_TYPE environment variable has been corrected.
Comments associated with environment variables should be accurate and not misleading.
Change to documentation, no testing necessary.
> Correct comment in sample.env for KAFKA_TYPE env var

- jpo-ode-common/pom.xml
- jpo-ode-core/pom.xml
- jpo-ode-plugins/pom.xml
- jpo-ode-svcs/pom.xml
- jpo-ode-svcs/run.bat
- jpo-ode-svcs/run.sh
- pom.xml
The version of the project has been changed to 2.1.0-SNAPSHOT in anticipation for the 2024 Q2 Release.
The version will need to be updated for the upcoming release and the sooner we do it the less we have to worry about bottleneck during the pom.xml reference updates for the projects.
- The program has been verified to compile with these changes.
- The unit tests have been verified to pass with these changes.
> Changed version to 2.1.0-SNAPSHOT

- docs/compatibility.md
A new release will be coming out this month, and the submodule compatibility guide has not been updated.
The submodule compatibility guide has been updated to inform users of submodule versions compatible with ODE v2.1.0
> Updated submodule compatibility guide for 2024 Q2 release

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/rsu/RsuDepositor.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/traveler/TimDeleteController.java
For deposits, we don't have an interpretation of the 'error code 10 wrong value' issue that can occur when running SNMP commands against an RSU. For deletes, the interpretation is cryptic and offers little guidance.
The ODE will now interpret failed deposits/deletes due to 'error code 10 wrong value' as a possible SNMP protocol mismatch and will inform the user to check the RSU configuration.
The unit tests have been verified to pass with these changes.
> Improve SNMP Error Code 10 Interpretation

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
The ODE will sometimes receive bad encoded data from the ACM (often due to the ACM running into a problem during processing) and at this time the ODE prints a stack trace regardless of the log level.
The Asn1EncodedDataRouter has been modified to print a stack trace in this case only if debug logging is enabled.
> Print stack trace upon receiving bad encoded data from ACM only if debug logging is enabled

- docs/release_process.md
Although the release process documentation advises developers to update project references, it lacks detailed, step-by-step instructions. Providing more granular guidance would make the process clearer for developers.
Section 3 of the quarterly release process documentation has been expanded to include more detailed instructions on updating project references. Furthermore, the creation of releases has been integrated into the process rather than being an afterthought.
> Expand Project Reference Update Documentation

- .devcontainer/Dockerfile
The dev container is currently failing to build during the step where the user is added due to the unique ID of 1000 already being taken.
The unique ID for the user has been changed to 1234 instead of 1000.
Additionally, a large multi-line step has been broken up into multiple steps. This will make it easier to see where the build failure is in the future.
The dev container should not fail to build.
The Dockerfile for the dev container has been verified to work with `docker build . --no-cache`, and reopening the project in the dev container through VSCode has also been verified to work.
> Fixed dev container build failure

- sample.env
In the sample.env file, the SDW_SUBSCRIPTION_TOPIC environment variable is incorrectly set to a TIM output topic instead of the 'topic.SDWDepositorInput' topic, which is defined in `jpo-ode-svcs\src\main\java\us\dot\its\jpo\ode\OdeProperties.java`. As a result, the default configuration for the ODE will not work as intended.
The SDW_SUBSCRIPTION_TOPIC environment variable in the sample.env file has now been updated to 'topic.SDWDepositorInput'.
> Set SDW_SUBSCRIPTION_TOPIC to 'topic.SDWDepositorInput'

- jpo-ode-core/src/main/resources/schemas/schema-map.json
- jpo-ode-core/src/main/resources/schemas/schema-spat.json
- jpo-ode-core/src/main/resources/schemas/schema-srm.json
- jpo-ode-core/src/main/resources/schemas/schema-ssm.json
- jpo-ode-core/src/main/resources/schemas/schema-tim.json
Updating the "recordGeneratedBy" schema definition to use the ENUM definition of the field as well as allow null values.
To fix good SRM type messages going to the DLQ in BigQuery and standardizing the message schemas for this field.
Testing known good messages with the updated schemas and verify that the schema validates the message properly.
- [ x ] All new and existing tests passed.
> ODE JSON Schema Updates

- .github/workflows/artifact-publish.yml
- jpo-ode-svcs/pom.xml
- pom.xml
- Creates a profile in the jpo-ode-svcs `pom.xml` that publishes a jar without the springboot dependencies for publishing java packages to GitHub maven repository.
- Build without unit tests as they will fail without supporting services in GitHub actions (kafka & kafka topics)
Draft PR for testing
N/A
https://github.com/usdot-jpo-ode/jpo-ode/pull/555#discussion_r1769063142
- By running a test trigger on the CDOT-CV fork and seeing the [published package](https://github.com/CDOT-CV/jpo-ode/packages/2205029) is now 212 kb.
- I also tested the standard dockerized build and that still produces the springboot based image and performs identically to before.
[ODE Contributing …
> Remove Sping Dependencies from Maven Jars

- docs/schemas/README.md
- jpo-ode-core/src/main/resources/schemas/schema-tim.json
This pull request updates the TIM schema to include all supported ODE fields. This maintains the ASN1 being an optional field.
N/A
The previous TIM schema was only partially supporting the possible ODE fields of a TIM. This caused TIMs that were perfectly acceptable to fail validation checks where schema validation was implemented.
This has been tested with live TIM data generated in the CDOT environment based off WZDx data.
> Update TIM schema

- jpo-ode-core/src/test/java/us/dot/its/jpo/ode/model/OdeTimDataTest.java
This includes a fix to the TIM schema test that was not updated when the TIM schema was updated. It properly updates the schema validator to validate the schema with the proper latest schema version "V202012".
N/A
The unit test was failing.
This has been tested locally.
> Update the TIM schema test

- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/SSMBuilder.java
- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/SignalStatusBuilder.java
- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/SignalStatusListBuilder.java
- jpo-ode-plugins/src/main/java/us/dot/its/jpo/ode/plugin/j2735/builders/SignalStatusPackageListBuilder.java
- jpo-ode-svcs/src/test/java/us/dot/its/jpo/ode/coder/OdeSsmDataCreatorHelperTest.java
This resolves issues with how arrays and certain fields were handled in parsing the ASN1 Codec's XML for SSM messages.
The following fields were addressed:
- payload.data.sequenceNumber
- payload.data.status.signalStatus
- payload.data.status.signalStatus.sigStatus.signalStatusPackage
No related USDOT issue
SSM messages are not currently being processed correctly and result in malformed SSM JSON being written to the topic.OdeSsmJson Kafka topic. This is a problem for all data analysts that need accurate SSM data for their reports.
This has been tested with real SSM data from the CDOT Region 1 snowplows.
> SSM Processing Fix

- .github/workflows/artifact-publish.yml
Switched the github jar builder distribution from adopt to temurin. This will fix broken github jar file generation caused by Adopt moving to a new location. https://api.adoptopenjdk.net/ . Temurin is used by other parts of the ODE and is more in line with the current way code is built in docker.
> Switching adopt builder to temurin

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/SerializableMessageProducerPool.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/coder/ByteArrayPublisher.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/coder/FileAsn1CodecPublisher.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1CommandManager.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1DecodedDataRouter.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeBSMJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodePSMJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSPATJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSRMJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeSSMJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/message/Asn1DecodeTIMJSON.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/json/ToJsonConverter.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/traveler/TimDepositController.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/bsm/BsmReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/generic/GenericReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/psm/PsmReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/spat/SpatReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/srm/SrmReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/ssm/SsmReceiver.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/tim/TimReceiver.java
Use the correct configuration value to drive the StringProducer creation. Previously was using the Producer Type where we should be using the Kafka Type. This mismatch caused the code not to set the Confluent properties on the StringProducers, so they couldn't connect to Confluent.
See description
@Michael7371 and I built and deployed this to the CDOT dev environment to confirm that the producers could connect and produce to the respective queues.
> BugFix: use correct config value for setting up producers with Confluent Properties

- jpo-ode-core/src/main/resources/schemas/schema-tim.json
…message field names
Resolves an issue for the TIM schema wherein the `NodeOffsetPointXY` and `NodeOffsetPointLL` schema objects are missing hyphens in their fields.
Example:
- Was: `nodeXY1`
- Now: `node-XY1`
N/A
The previous TIM schema did not accurately portray the output of the jpo-ode 4.0.0 OdeTimJson message which is misleading and fails schema validation checks when the fields are included.
Locally with unit tests and online JSON schema validators.
> Resolve TIM schema inconsistency

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/kafka/producer/KafkaProducerConfig.java
Set `linger.ms` to 1 millisecond to prevent producer failures.
During CDOT GCP dev testing, we encountered many `ERROR LoggingProducerListener - Failed to produce to topic` errors in the logs specifically associated with Spring Kafka-managed producers. This is not ideal
Deployed to CDOT GCP dev and watched the logs to confirm the exceptions were no longer thrown.
> Fix: producer failures

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/kafka/producer/KafkaProducerConfig.java
- jpo-ode-svcs/src/main/resources/application.yaml
Use environment variables to drive producer retries for consistency with non-spring kafka producer configurations
To keep the Spring Kafka producers and legacy producers configurations consistent.
I spun up the docker compose with profile `all` locally to confirm the environment variables are set correctly and the Spring Kakfa producers are using the same values for retries.
> Fix: Use odeKafkaProperties env vars to drive producer retries

- docs/compatibility.md
An entry has been added to the Submodule Compatibility Guide for the 2025 Q1 Release. The following table outlines the actions taken regarding version changes for each project:
| Project | Action | New Version |
| --- | --- | --- |
| jpo-ode | major version incremented | 4.0.0 |
| asn1_codec | major version incremented | 3.0.0 |
| jpo-cvdp | minor version incremented | 1.5.0 |
| jpo-security-svcs | no change | 1.5.0 |
| jpo-sdw-depositor | minor version incremented | 1.9.0 |
| jpo-s3-deposit | minor version incremented | 1.7.0 |
| jpo-geojsonconverter | major version incremented | 2.0.0 |
| jpo-conflictmonitor | major version incremented | 2.0.0 |
| jpo-conflictvisualizer | minor version incremented | 1.5.0 |
| jpo-cvmanager | minor version incremented | 1.5.0 | …
> Updated Submodule Compatibility Guide for 2025 Q1 Release

- jpo-ode-core/src/main/resources/schemas/schema-psm.json
- jpo-ode-core/src/test/java/us/dot/its/jpo/ode/model/OdePsmDataTest.java
- jpo-ode-core/src/test/resources/json/sample-psm.json
Updates the "recordGeneratedBy" field in the PSM schema to be the same as the BSM schema to allow String values specified in [OdeLogMetadata](https://github.com/CDOT-CV/jpo-ode/blob/dev/jpo-ode-core/src/main/java/us/dot/its/jpo/ode/model/OdeLogMetadata.java).
N/A
Allow PSM messages to pass schema validation
Checking PSM schema validation failed with the old schema and succeeds with this schema (used the sample message in the [udpsender_psm.py](https://github.com/CDOT-CV/jpo-ode/blob/dev/scripts/tests/udpsender_psm.py) script
- [ x ] I have added tests …
> PSM Schema Fix

- docs/Release_notes.md
This pull request updates the 2025 Q1 release notes to reflect changes made for partial compatibility with J2735 2024. Schema updates have been implemented to increment the version of output messages. However, due to a bug in the ASN.1 Compiler, the VehicleEventFlags bitstring has been reverted to its 2020 version, meaning the new eventJackKnife bit from the 2024 revision will not appear in output BSMs until the issue is resolved. Additionally, some new fields introduced in J2735 2024 for BSM-related structures are not yet supported in the ODE but will be included in a future release.
J2735 2024 includes updates that require changes to message structures, and we’ve made progress in supporting these updates. While there are some known limitations, like the missing …
> Updated 2025 Q1 Release Notes to Reflect Partial J2735 2024 Compatibility

- docs/Release_notes.md
- jpo-ode-common/src/main/java/us/dot/its/jpo/ode/util/JsonUtils.java
- jpo-ode-core/src/main/resources/schemas/schema-map.json
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/config/SerializationConfig.java
Configure the ObjectMappers used by the ToJsonConverter and KafkaTemplates to serialize BigDecimal fields as numbers instead of (occasionally) Strings.
Before:
```json
{
...
"accelSet": {
"accelLat": 2001,
"accelLong": -0.33,
"accelVert": -127,
"accelYaw": -0.23
},
"accuracy": {
"semiMajor": "2.00",
"semiMinor": "2.00",
"orientation": "0E-10"
}
}
...
}
```
After:
```json
{
...
"accelSet": {
"accelLat": 2001,
"accelLong": -0.33,
"accelVert": -127,
"accelYaw": -0.23
},
"accuracy": {
"semiMajor": 2.00,
"semiMinor": 2.00,
"orientation": 0.0000000000
}
}
...
}
```
Also, update the map json schema to align with the ASN1 spec by updating the data type from string to number
> The DE_Elevation data element represents the geographic position above or below the reference ellipsoid (typically …
> fix: force BigDecimal serialization to NUMBER format

- jpo-ode-common/src/main/java/us/dot/its/jpo/ode/inet/InetPoint.java
- jpo-ode-common/src/test/java/us/dot/its/jpo/ode/inet/InetPacketFunctionalTest.java
- Use `@Slf4j` annotation to construct logger in InetPoint to prevent flaky errors in tests
- Address Checkstyle violations in changed files (formatting, javadocs)
- Update InetPacketFunctionalTest to consistently use `junit.jupiter.api` 
This should address a flaky test failure we saw in https://github.com/usdot-jpo-ode/jpo-ode/actions/runs/12918350007/job/36079870160?pr=562
> Fix: update InetPacketFunctionalTest to prevent flaky test failures

- .azure/README.md
- .azure/azure-pipelines.yml
Include the Git history in Azure artifacts to allow for tagging the built image with the latest git commit SHA.
N/A
Adds more traceability in our built images to know what source code is associated with the built images.
A test build and push has been triggered off of this PR:
> Include Git History in Azure Artifacts

- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/services/asn1/Asn1EncodedDataRouter.java
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/udp/controller/UdpServicesController.java
- Improve thread management in the UdpServicesController.
- Add offsets to improve logging of Asn1EncodedDataRouter consumption from the AEM. This helps us identify the message on the topic so that we can inspect it and identify any issues.
A combination of changes in the Spring Kafka migration PRs caused the UDP Receiver thread management to fail. The threads were created, but the BSMReceiver thread was blocking the execution of the other receivers. We need the receivers to run on separately managed threads so that we can consume UDP data independently.
I have locally deployed the ODE and stepped through with a debugger to confirm data is consumed from the UDP endpoints correctly. I ran the udp_sender scripts for each message type.
I have also deployed a development build docker image to …
> Fix: UDP Receiver thread management

- Dockerfile
- jpo-ode-svcs/src/main/java/us/dot/its/jpo/ode/OdeTimJsonTopology.java
This PR addresses a resource usage bug resulting from using an in-memory store for the OdeTimJson k-table. This has been updated to use a persistent store, bringing the JVM heap usage down from ~99% to ~30%. 
This update prevents pod restarts and out of memory errors in the ODE due to the OdeTimJson k-table. 
This has been tested locally using docker compose and was deployed/tested in the CDOT dev environment. During testing in dev, heap usage hovered around 30%. Additionally, I verified that messages were still being correctly produced to topic.OdeTimJsonTMCFiltered. 
- [ X ] Defect fix (non-breaking change that fixes an issue)
- [ X ] I have read the **CONTRIBUTING** document.
[ODE Contributing Guide](https://github.com/usdot-jpo-ode/jpo-ode/blob/develop/docs/contributing_guide.md) 
- [ …
> K-Table Memory Usage Bugfix

- pom.xml
The scm tag in the pom.xml still uses 4.0.0
The scm tag in the pom.xml has been updated to use 4.1.0
Verified successful compilation and unit tests passing
> Update scm tag in pom.xml

- docs/release_process_quarterly.md
This PR adds a missing step to section 3 of the jpo-utils quarterly release instructions.
> docs: add missing step to jpo-utils quarterly release instructions

- docs/release_process_quarterly.md
Some steps related to Docker image creation, pushing & tagging is not present in the jpo-utils section of the quarterly release documentation.
Missing steps have been added.
> docs: add missing docker image steps to jpo-utils section

- .github/workflows/ci.yml
Modifies the sonar CI job to only run when the target branch is owned by the usdot-jpo-ode organization.
> Modify Sonar CI Job
